In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
#scalar
scalar = torch.tensor (7)
scalar

tensor(7)

In [7]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
#matrix
matrix = torch.tensor(([7,8],[9,10]))
matrix


tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
matrix.ndim

2

In [12]:
matrix[0]

tensor([7, 8])

In [13]:
matrix[1]

tensor([ 9, 10])

In [14]:
matrix.shape

torch.Size([2, 2])

In [15]:
#tensor
tensor = torch.tensor([[[1, 2, 3],
                        [3,6,9],
                        [2,4,5]]])
tensor



tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [16]:
tensor.ndim

3

In [17]:
tensor.shape

torch.Size([1, 3, 3])

In [19]:
tensor = torch.tensor([[[1, 2, 3,4],
                        [3,6,9,7],
                        [2,4,5,8],
                        [4,6,8,1]]])
tensor


tensor([[[1, 2, 3, 4],
         [3, 6, 9, 7],
         [2, 4, 5, 8],
         [4, 6, 8, 1]]])

In [20]:
tensor.ndim



3

In [21]:
tensor.shape

torch.Size([1, 4, 4])

In [22]:
#Random Tensors
random=torch.rand(2,2)
random


tensor([[0.6037, 0.2713],
        [0.2145, 0.1976]])

In [23]:
random.ndim

2

In [24]:
#create a random tensor with similar shape to an image tensor
random=torch.rand(size=(2,3,3)) #height, width, color channel(RGB)
random.shape, random.ndim


(torch.Size([2, 3, 3]), 3)

In [25]:
random.dtype

torch.float32

In [28]:
#range of tensors
array=torch.arange(start=1, end=10, step=1)
array



tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
ten = torch.ones_like(input=array)
ten

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [32]:
#tensor datatypes
xyz=torch.tensor([3.0,6.0,9.0], 
                 dtype=None, device=None, requires_grad=False)
xyz

tensor([3., 6., 9.])