In [46]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:
#NumPy array to Tensor
array=np.arange(1,8)
tensor=torch.from_numpy(array)
array, tensor

(array([1, 2, 3, 4, 5, 6, 7]),
 tensor([1, 2, 3, 4, 5, 6, 7], dtype=torch.int32))

In [3]:
array= array+1
array, tensor

(array([2, 3, 4, 5, 6, 7, 8]),
 tensor([1, 2, 3, 4, 5, 6, 7], dtype=torch.int32))

In [5]:
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [6]:
#Change the tensor
tensor=tensor+1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [9]:
#Reproducibility
a = torch.rand(3,4)
b = torch.rand(3,4)
print(a)
print(b)
print(a==b)


tensor([[0.0915, 0.8996, 0.1459, 0.6715],
        [0.6583, 0.4828, 0.0663, 0.9361],
        [0.3121, 0.3531, 0.5815, 0.3318]])
tensor([[0.6016, 0.2185, 0.9733, 0.2521],
        [0.8635, 0.4167, 0.2203, 0.7276],
        [0.4203, 0.7219, 0.7154, 0.4948]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [16]:
random_seed=50
torch.manual_seed(random_seed)
c= torch.rand(3,4)
torch.manual_seed(random_seed)
d= torch.rand(3,4)
print(c)
print(d)
print(c==d)

tensor([[0.6180, 0.0687, 0.3893, 0.0404],
        [0.4013, 0.1442, 0.4605, 0.4877],
        [0.5927, 0.9634, 0.1230, 0.4048]])
tensor([[0.6180, 0.0687, 0.3893, 0.0404],
        [0.4013, 0.1442, 0.4605, 0.4877],
        [0.5927, 0.9634, 0.1230, 0.4048]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [47]:
#Running tensors and Pytorch objects on the GPUs making faster computation

torch.cuda.is_available()




False

In [44]:
device="cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [39]:
device ='cuda' if torch.cuda.is_available else'cpu'
device

'cuda'