In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#tensor datatypes
xyz=torch.tensor([3.0,6.0,9.0], 
                 dtype=None, device=None, requires_grad=False)
xyz

tensor([3., 6., 9.])

In [4]:
xyz.dtype

torch.float32

In [5]:
abc=xyz.type(torch.float16)
abc

tensor([3., 6., 9.], dtype=torch.float16)

In [6]:
xyz*abc

tensor([ 9., 36., 81.])

In [7]:
intdtype=torch.tensor([3,6,9], dtype=torch.int64)
intdtype

tensor([3, 6, 9])

In [8]:
xyz*intdtype

tensor([ 9., 36., 81.])

In [9]:
#create a tensor
tensor = torch.rand(3,4)
tensor


tensor([[0.6791, 0.4518, 0.2173, 0.1130],
        [0.5962, 0.4376, 0.1078, 0.2114],
        [0.1546, 0.6443, 0.9080, 0.1508]])

In [10]:
print(tensor)
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Shape of tensor: {tensor.shape}")
print(f"Device of tensor is on: {tensor.device}")

tensor([[0.6791, 0.4518, 0.2173, 0.1130],
        [0.5962, 0.4376, 0.1078, 0.2114],
        [0.1546, 0.6443, 0.9080, 0.1508]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor is on: cpu


In [19]:
#manipulating tensors
#addition
tensor=torch.tensor([1,2,3])
tensor+10


tensor([11, 12, 13])

In [12]:
#substraction
tensor=torch.tensor([10,20,30])
tensor-5

tensor([ 5, 15, 25])

In [15]:
#multiplication
tensor*3

tensor([3, 6, 9])

In [16]:
#Pytorch built in function
torch.mul(tensor,3)

tensor([3, 6, 9])

In [25]:
#Matrix multiplication
print (tensor,"*", tensor)
print(f"Equals: {tensor*tensor}")


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [26]:
torch.matmul(tensor, tensor)

tensor(14)

In [28]:
#traditional way
value = 0
for i in range(len(tensor)):
    value+=tensor[i]*tensor[i]
print(value)

tensor(14)


In [ ]:
#One of the most common error in deep learning
#shape error - inner dimension have to be same/outer diension = result 
