In [1]:
import torch
print(torch.__version__)

1.12.1


In [2]:
#Random Array
a = torch.rand(5,5)
print(a)

tensor([[0.4491, 0.2945, 0.2503, 0.5021, 0.4476],
        [0.0017, 0.8330, 0.2157, 0.2501, 0.4564],
        [0.8125, 0.1361, 0.3499, 0.1858, 0.3240],
        [0.0643, 0.0687, 0.8388, 0.7117, 0.6158],
        [0.4463, 0.2683, 0.7111, 0.5022, 0.1914]])


In [4]:
device ='cuda' if torch.cuda.is_available else'cpu'


In [5]:
device

'cuda'

In [6]:
randarra = torch.rand((3,2), dtype = torch.float32)
randarra

tensor([[0.0813, 0.1774],
        [0.6893, 0.0706],
        [0.1663, 0.9134]])

In [8]:
#Eye Array
eyearray = torch.eye(4,2)
eyearray


tensor([[1., 0.],
        [0., 1.],
        [0., 0.],
        [0., 0.]])

In [9]:
#One's Array
onesarray= torch.ones(4,4)
onesarray

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [12]:
#Arrange Data
arrdata = torch.arange(start=0,end=11,step=2)
arrdata

tensor([ 0,  2,  4,  6,  8, 10])

In [17]:
#Multiply two arrays
x= torch.rand(4,4)
x

tensor([[0.8242, 0.7558, 0.9127, 0.7851],
        [0.9247, 0.8880, 0.2976, 0.3964],
        [0.3410, 0.2053, 0.1129, 0.7037],
        [0.8628, 0.4283, 0.0169, 0.1623]])

In [18]:
y=torch.rand(4,4)
y


tensor([[0.1653, 0.2477, 0.2477, 0.7516],
        [0.1249, 0.4895, 0.7118, 0.9556],
        [0.4976, 0.8692, 0.0763, 0.9683],
        [0.9199, 0.2597, 0.1614, 0.2198]])

In [19]:
x*y


tensor([[0.1363, 0.1872, 0.2260, 0.5900],
        [0.1155, 0.4347, 0.2118, 0.3788],
        [0.1697, 0.1784, 0.0086, 0.6814],
        [0.7937, 0.1112, 0.0027, 0.0357]])