In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [22]:
#find min
x= torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [6]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [8]:
#find max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [24]:
#find mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [26]:
#find sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [28]:
#minmax index
torch.argmax(x)

tensor(9)

In [29]:
x.argmin()

tensor(0)

In [36]:
#reshaping
x= torch.arange(1,10)
x, x.shape
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [37]:
#view
z=x.view(1,9)
z, z.shape


(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [38]:
z[:,0]=5
z,x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [43]:
#Stacking
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked


tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [50]:
#squeezing
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

x_squeezed = x_reshaped.squeeze()
print(f"\n New tensor: {x_squeezed}")
print(f"\n New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
Previous shape: torch.Size([9, 1])

 New tensor: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])

 New shape: torch.Size([9])


In [53]:
#unsqueezing
print(f"previous target: {x_squeezed}")
print(f"previous shape: {x_squeezed.shape}")
unsq = x_squeezed.unsqueeze(dim=1)
print(f"\n New tensor: {unsq}")
print(f"\n New tensor shape: {unsq.shape}")


previous target: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
previous shape: torch.Size([9])

 New tensor: tensor([[5],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

 New tensor shape: torch.Size([9, 1])


In [55]:
#permute
y=torch.rand(size=(1,2,3))
y_perm= y.permute(2,0,1)
print(f"Previous shape: {y.shape}")
print(f"New shape: {y_perm.shape}")

Previous shape: torch.Size([1, 2, 3])
New shape: torch.Size([3, 1, 2])


In [58]:
#indexing
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [59]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [68]:
x[0,1]

tensor([4, 5, 6])

In [73]:
x[0,2,2]

tensor(9)

In [88]:
#select one dim
x[:,2]
#select first two dim and first index of last dim
x[0, 1, 1]

tensor(5)

In [90]:
#NumPy array to Tensor
array=np.arange(1,8)
tensor=torch.from_numpy(array)
array, tensor


(array([1, 2, 3, 4, 5, 6, 7]),
 tensor([1, 2, 3, 4, 5, 6, 7], dtype=torch.int32))